### PR TITLE
Directory reorg to better match release, and fix for case-insensitive…

### PR DESCRIPTION
**Pull request by proberon**
… filesystems

### CODE REVIEW

**Comment by k-john-gough** [comment]
Hi proberon. I understand the idea of reorganizing the directories. Unfortunately there is an enormous number of lines showing in the diff that seem to just be a move of the unchanged file. I need to know which file(s) has the changes which embody the "fix for case-insensitive filesystems".
I am in the process of preparing changes to the master branch, and I would like I would like to keep the merges separate.

**Comment by proberon** [comment]
Yup, sorry for the confusion, I should indeed have done them separately - the case-insensitive filesystems fix was merely to merge the two J2CPS directories, which differed only in case. No file contents were changed at all. Apologies!

**Comment by proberon** [comment]
Anyway, you get the idea, no need to pull - my suggestion was to move the root of the repo into a directory called sources (to correspond with the release structure), merge the j2cps directories, and then move my two "env" setup scripts back out to the root. Is all. :)

**Comment by ghost** [comment]
> Anyway, you get the idea, no need to pull - my suggestion was to move the root of the repo into a directory called sources (to correspond with the release structure), merge the j2cps directories, and then move my two "env" setup scripts back out to the root. Is all. :)

You will have to close this PR and open a new PR. The old and retired professor will not do that for you even if he got your idea. As he said, you seem to need split this PR into 2 separate PRs.

**Comment by ghost** [comment]
#5

**Comment by proberon** [comment]
"Yup, sorry for the confusion, I should indeed have done them separately - the case-insensitive filesystems fix was merely to merge the two J2CPS directories, which differed only in case. No file contents were changed at all. Apologies!"

**Comment by ghost** [comment]
> "Yup, sorry for the confusion, I should indeed have done them separately - the case-insensitive filesystems fix was merely to merge the two J2CPS directories, which differed only in case. No file contents were changed at all. Apologies!"

@proberon Could you make a new PR for the case-insensitive filesystems fix? I'm on Windows, and I have real troubles when trying to apply the patches by @pahihu. I ended up having to cherry-pick and apply everything manually on Github web interface.

**Comment by proberon** [comment]
I feel your pain. As I said, the pull request would be: "merge the two J2CPS directories". I think Prof. Gough understands that.

Unfortunately, when I did this through git, it resulted in "150 changed files with 58,550 additions and 58,550 deletions" which considerably confused the issue and he quite rightly didn't want to accept it. I really don't want to generate that much noise again!

**Comment by ghost** [comment]
> I feel your pain. As I said, the pull request would be: "merge the two J2CPS directories". I think Prof. Gough understands that.
> 
> Unfortunately, when I did this through git, it resulted in "150 changed files with 58,550 additions and 58,550 deletions" which considerably confused the issue and he quite rightly didn't want to accept it. I really don't want to generate that much noise again!

I found the directory `j2cps` only contains an `ant` build script (`build.xml`). Could this `build.xml` be moved into `J2CPS` and the directory `j2cps` could be safety deleted?

**Comment by ghost** [comment]
Update: I decided to move `build.xml` into `J2CPS` and delete `j2cps` in my PRs.

**Pull request closed without merging**
